export const categories = [
  { value: "smartphones", label: "Smartphones" },
  { value: "laptops", label: "Laptops" },
  { value: "fragrances", label: "Fragrances" },
  { value: "skincare", label: "Skincare" },
  { value: "groceries", label: "Groceries" },
  { value: "home-decoration", label: "Home-Decoration" },
  { value: "furniture", label: "Furniture" },
  { value: "tops", label: "Tops" },
  { value: "womens-dresses", label: "Womens-Dresses" },
  { value: "womens-shoes", label: "Womens-Shoes" },
  { value: "mens-shirts", label: "Mens-Shirts" },
  { value: "mens-shoes", label: "Mens-Shoes" },
  { value: "mens-watches", label: "Mens-Watches" },
  { value: "womens-watches", label: "Womens-Watches" },
  { value: "womens-bags", label: "Womens-Bags" },
  { value: "womens-jewellery", label: "Womens-Jewellery" },
  { value: "sunglasses", label: "Sunglasses" },
  { value: "automotive", label: "Automotive" },
  { value: "motorcycle", label: "Motorcycle" },
  { value: "lighting", label: "Lighting" },
];
